CREATE TABLE tracks (
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    popularity INTEGER,
    duration_ms INTEGER,
    explicit BOOLEAN,
    artists JSON,
    id_artists JSON,
    release_date DATE,
    danceability VARCHAR(255),
    energy NUMERIC,
    key INTEGER,
    loudness NUMERIC,
    mode INTEGER,
    speechiness NUMERIC,
    acousticness NUMERIC,
    instrumentalness NUMERIC,
    liveness NUMERIC,
    valence NUMERIC,
    tempo NUMERIC,
    time_signature INTEGER,
    year VARCHAR(4),
    month VARCHAR(2),
    day VARCHAR(2)
);
